### ISSUE TITLE
Uncaught Error: Class 'Dotenv\Dotenv'

### ISSUE THREAD

**Issue by gustavpursche** [pivvenit/acf-composer-bridge#10]
Hi.
When running `composer install` without existing `vendor/` directory the following errors appears:

```
PHP Fatal error:  Uncaught Error: Class 'Dotenv\Dotenv' not found in /home/gustav/Development/analyse-und-kritik/vendor/pivvenit/acf-pro-installer/src/LicenseKey/Providers/DotEnv/DotEnvV3Adapter.php:18
Stack trace:
#0 /home/gustav/Development/analyse-und-kritik/vendor/pivvenit/acf-pro-installer/src/LicenseKey/Providers/DotEnv/DotEnvLicenseKeyProvider.php(27): PivvenIT\Composer\Installers\ACFPro\LicenseKey\Providers\DotEnv\DotEnvV3Adapter->load()
#1 /home/gustav/Development/analyse-und-kritik/vendor/pivvenit/acf-pro-installer/src/LicenseKey/Providers/CompositeLicenseKeyProvider.php(29): PivvenIT\Composer\Installers\ACFPro\LicenseKey\Providers\DotEnv\DotEnvLicenseKeyProvider->provide()
#2 /home/gustav/Development/analyse-und-kritik/vendor/pivvenit/acf-pro-installer/src/ACFProInstallerPlugin.php(156): PivvenIT\Composer\Installers\ACFPro\LicenseKey\Providers\CompositeLicenseKeyProvider->provide()
#3 /home/gustav/Development/analyse-und-kritik/vendor/pivvenit/acf-pro-installer/src/ACFProInstallerPlugin.php(142): PivvenIT\Composer\I in /home/gustav/Development/analyse-und-kritik/vendor/pivvenit/acf-pro-installer/src/LicenseKey/Providers/DotEnv/DotEnvV3Adapter.php on line 18
```

When I run `composer install` again, it all works fine. Is this a problem on my machine?

**Comment by Qrious** [comment]
Hi,

Sorry for the delayed response. I'm not getting any notifications of issues created at [pivvenit/acf-composer-bridge](https://github.com/pivvenit/acf-composer-bridge) for some reason :(. 

It might be due to a dependency installation issue with Composer 2. I'll try to reproduce.
